const Map<String, Map<String, String>> _strings = {
  'ja': {
    'app.title': 'たからさがし',
    'home.title': 'たからの ちず',
    'home.locked': 'ロック',
    'home.cleared': 'クリア',
    'settings.title': 'せってい',
    'settings.language': 'ことば',
    'seek.complete': 'クリア！！\n全て みつけたね',
    'scene.scene01.title': 'もりの たからさがし',
    'scene.scene02.title': 'うみの たからさがし',
    'scene.scene03.title': 'そらの たからさがし',
    'scene.scene04.title': 'やまの たからさがし',
    'scene.scene05.title': 'よるの たからさがし',
    'target.apple': 'りんご',
    'target.duck': 'あひる',
    'target.star': 'ほし',
    'target.ball': 'ボール',
    'target.flower': 'おはな',
    'target.heart': 'ハート',
    'seek.toMap': 'ちずに もどる',
    'slot.title': 'だれが あそぶ?',
    'slot.new': 'あたらしく',
    'slot.continue': 'つづき',
    'slot.reset': 'リセット',
  },
  'en': {
    'app.title': 'Treasure Hunt',
    'home.title': 'Treasure Map',
    'home.locked': 'Locked',
    'home.cleared': 'Cleared',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'seek.complete': 'Clear!!\nYou found them all!',
    'scene.scene01.title': 'Forest Hunt',
    'scene.scene02.title': 'Ocean Hunt',
    'scene.scene03.title': 'Sky Hunt',
    'scene.scene04.title': 'Mountain Hunt',
    'scene.scene05.title': 'Night Hunt',
    'target.apple': 'Apple',
    'target.duck': 'Duck',
    'target.star': 'Star',
    'target.ball': 'Ball',
    'target.flower': 'Flower',
    'target.heart': 'Heart',
    'seek.toMap': 'Back to map',
    'slot.title': 'Who is playing?',
    'slot.new': 'New',
    'slot.continue': 'Continue',
    'slot.reset': 'Reset',
  },
};

/// localeCode('ja'|'en') と key から表示文字列を返す。未定義は ja → key の順でフォールバック。
String tr(String localeCode, String key) {
  return _strings[localeCode]?[key] ?? _strings['ja']?[key] ?? key;
}
