const Map<String, Map<String, String>> _strings = {
  'ja': {
    'app.title': 'たからさがし',
    'home.title': 'たからの ちず',
    'home.locked': 'ロック',
    'home.cleared': 'クリア',
    'home.modeEasy': 'やさしい',
    'home.modeNormal': 'ふつう',
    'home.modeHard': 'むずかしい',
    'home.collection': 'ずかん',
    'collection.title': 'たからの ずかん',
    'collection.collected': 'あつめた',
    'collection.allDone': 'ぜんぶ あつめたね！',
    'collection.new': 'NEW',
    'collection.rare': 'とくべつ',
    'collection.byWorld': 'ワールド',
    'collection.byCategory': 'なかま',
    'rare.found': '✨ とくべつ！ ✨',
    'rare.gem': 'ほうせき',
    'rare.crown': 'おうかん',
    'rare.medal': 'メダル',
    'settings.title': 'せってい',
    'settings.language': 'ことば',
    'settings.trailColor': 'なぞった ときの いろ',
    'trailColor.sky': 'みずいろ',
    'trailColor.pink': 'ピンク',
    'trailColor.yellow': 'きいろ',
    'trailColor.purple': 'むらさき',
    'trailColor.orange': 'オレンジ',
    'trailColor.white': 'しろ',
    'trailColor.red': 'あか',
    'trailColor.green': 'みどり',
    'trailColor.teal': 'みずみどり',
    'trailColor.lime': 'きみどり',
    'trailColor.brown': 'ちゃいろ',
    'trailColor.black': 'くろ',
    'trailColor.indigo': 'あいいろ',
    'trailColor.magenta': 'マゼンタ',
    'trailColor.coral': 'コーラル',
    'trailColor.mint': 'ミント',
    'trailColor.lavender': 'ラベンダー',
    'trailColor.peach': 'ピーチ',
    'trailColor.turquoise': 'ターコイズ',
    'trailColor.grey': 'グレー',
    'trailStyle.solid': 'シンプル',
    'trailStyle.rainbow3': 'カラフル',
    'trailStyle.rainbowFull': 'レインボー',
    'trailStyle.rainbowFull.hint': 'なぞると にじいろ',
    'trailStyle.rainbow3.lockedHint': 'やさしいを ぜんぶ クリアすると つかえるよ',
    'trailStyle.rainbowFull.lockedHint': 'むずかしいを ぜんぶ クリアすると つかえるよ',
    'trailColor.pick3': '3つ えらぶ',
    'trailColor.slot1': '1つめ',
    'trailColor.slot2': '2つめ',
    'trailColor.slot3': '3つめ',
    'seek.complete': 'クリア！！\nぜんぶ みつけたね',
    'scene.scene01.title': 'もりの たからさがし',
    'scene.scene02.title': 'うみの たからさがし',
    'scene.scene03.title': 'そらの たからさがし',
    'scene.scene04.title': 'やまの たからさがし',
    'scene.scene05.title': 'よるの たからさがし',
    'scene.scene06.title': 'さばくの たからさがし',
    'scene.scene07.title': 'うちゅうの たからさがし',
    'scene.scene08.title': 'うみのなかの たからさがし',
    'scene.scene09.title': 'ゆきやまの たからさがし',
    'scene.scene10.title': 'はなばたけの たからさがし',
    'scene.scene11.title': 'にじのおかの たからさがし',
    'scene.scene12.title': 'おしろの たからさがし',
    'scene.scene13.title': 'ぎんがの たからさがし',
    'target.apple': 'りんご',
    'target.duck': 'あひる',
    'target.star': 'ほし',
    'target.ball': 'ボール',
    'target.flower': 'おはな',
    'target.heart': 'ハート',
    'target.fox': 'きつね',
    'target.owl': 'ふくろう',
    'target.butterfly': 'ちょうちょ',
    'target.bird': 'とり',
    'target.squirrel': 'りす',
    'target.hedgehog': 'はりねずみ',
    'target.crab': 'かに',
    'target.starfish': 'ひとで',
    'target.fish': 'さかな',
    'target.octopus': 'たこ',
    'target.seahorse': 'タツノオトシゴ',
    'target.jellyfish': 'くらげ',
    'target.penguin': 'ペンギン',
    'target.camel': 'らくだ',
    'target.snake': 'へび',
    'target.bee': 'はち',
    'target.firefly': 'ホタル',
    'target.astronaut': 'うちゅうひこうし',
    'target.mushroom': 'きのこ',
    'target.acorn': 'どんぐり',
    'target.shell': 'かいがら',
    'target.pinetree': 'まつのき',
    'target.cactus': 'サボテン',
    'target.sun': 'たいよう',
    'target.snowman': 'ゆきだるま',
    'target.sunflower': 'ひまわり',
    'target.trafficlight': 'しんごう',
    'target.house': 'いえ',
    'target.comet': 'すいせい',
    'target.pyramid': 'ピラミッド',
    'target.planet': 'わくせい',
    'target.snowflake': 'ゆきのけっしょう',
    'target.rainbow': 'にじ',
    'target.flag': 'はた',
    'target.saturn': 'どせい',
    'target.galaxy': 'ぎんが',
    'target.bucket': 'バケツ',
    'target.balloon': 'ふうせん',
    'target.bus': 'バス',
    'target.backpack': 'リュック',
    'target.rocket': 'ロケット',
    'target.ufo': 'UFO',
    'target.mitten': 'てぶくろ',
    'target.sled': 'そり',
    'target.shield': 'たて',
    'seek.toMap': 'ちずに もどる',
    'seek.move': 'うごかす',
    'seek.trace': 'なぞる',
    'quest.animal': 'どうぶつ',
    'quest.food': 'たべもの',
    'quest.shape': 'かたち',
    'quest.toy': 'おもちゃ',
    'quest.nature': 'おはな',
    'slot.title': 'だれが あそぶ?',
    'slot.new': 'あたらしく',
    'slot.continue': 'つづき',
    'slot.reset': 'リセット',
    'slot.free': 'フリーモード',
    'slot.pick': 'どれに する?',
    'slot.cancel': 'もどる',
    'slot.changeAvatar': 'えを かえる',
  },
  'en': {
    'app.title': 'Treasure Hunt',
    'home.title': 'Treasure Map',
    'home.locked': 'Locked',
    'home.cleared': 'Cleared',
    'home.modeEasy': 'Easy',
    'home.modeNormal': 'Normal',
    'home.modeHard': 'Hard',
    'home.collection': 'Collection',
    'collection.title': 'Treasure Collection',
    'collection.collected': 'Collected',
    'collection.allDone': 'All collected!',
    'collection.new': 'NEW',
    'collection.rare': 'Special',
    'collection.byWorld': 'Worlds',
    'collection.byCategory': 'Kinds',
    'rare.found': '✨ Special! ✨',
    'rare.gem': 'Gem',
    'rare.crown': 'Crown',
    'rare.medal': 'Medal',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.trailColor': 'Trail color',
    'trailColor.sky': 'Sky',
    'trailColor.pink': 'Pink',
    'trailColor.yellow': 'Yellow',
    'trailColor.purple': 'Purple',
    'trailColor.orange': 'Orange',
    'trailColor.white': 'White',
    'trailColor.red': 'Red',
    'trailColor.green': 'Green',
    'trailColor.teal': 'Teal',
    'trailColor.lime': 'Lime',
    'trailColor.brown': 'Brown',
    'trailColor.black': 'Black',
    'trailColor.indigo': 'Indigo',
    'trailColor.magenta': 'Magenta',
    'trailColor.coral': 'Coral',
    'trailColor.mint': 'Mint',
    'trailColor.lavender': 'Lavender',
    'trailColor.peach': 'Peach',
    'trailColor.turquoise': 'Turquoise',
    'trailColor.grey': 'Grey',
    'trailStyle.solid': 'Simple',
    'trailStyle.rainbow3': 'Colorful',
    'trailStyle.rainbowFull': 'Rainbow',
    'trailStyle.rainbowFull.hint': 'Cycles through the rainbow',
    'trailStyle.rainbow3.lockedHint': 'Clear all Easy scenes to unlock',
    'trailStyle.rainbowFull.lockedHint': 'Clear all Hard scenes to unlock',
    'trailColor.pick3': 'Pick 3 colours',
    'trailColor.slot1': '1st',
    'trailColor.slot2': '2nd',
    'trailColor.slot3': '3rd',
    'seek.complete': 'Clear!!\nYou found them all!',
    'scene.scene01.title': 'Forest Hunt',
    'scene.scene02.title': 'Ocean Hunt',
    'scene.scene03.title': 'Sky Hunt',
    'scene.scene04.title': 'Mountain Hunt',
    'scene.scene05.title': 'Night Hunt',
    'scene.scene06.title': 'Desert Hunt',
    'scene.scene07.title': 'Space Hunt',
    'scene.scene08.title': 'Undersea Hunt',
    'scene.scene09.title': 'Snowy Hunt',
    'scene.scene10.title': 'Flower Field Hunt',
    'scene.scene11.title': 'Rainbow Hills Hunt',
    'scene.scene12.title': 'Castle Hunt',
    'scene.scene13.title': 'Galaxy Hunt',
    'target.apple': 'Apple',
    'target.duck': 'Duck',
    'target.star': 'Star',
    'target.ball': 'Ball',
    'target.flower': 'Flower',
    'target.heart': 'Heart',
    'target.fox': 'Fox',
    'target.owl': 'Owl',
    'target.butterfly': 'Butterfly',
    'target.bird': 'Bird',
    'target.squirrel': 'Squirrel',
    'target.hedgehog': 'Hedgehog',
    'target.crab': 'Crab',
    'target.starfish': 'Starfish',
    'target.fish': 'Fish',
    'target.octopus': 'Octopus',
    'target.seahorse': 'Seahorse',
    'target.jellyfish': 'Jellyfish',
    'target.penguin': 'Penguin',
    'target.camel': 'Camel',
    'target.snake': 'Snake',
    'target.bee': 'Bee',
    'target.firefly': 'Firefly',
    'target.astronaut': 'Astronaut',
    'target.mushroom': 'Mushroom',
    'target.acorn': 'Acorn',
    'target.shell': 'Shell',
    'target.pinetree': 'Pine tree',
    'target.cactus': 'Cactus',
    'target.sun': 'Sun',
    'target.snowman': 'Snowman',
    'target.sunflower': 'Sunflower',
    'target.trafficlight': 'Traffic light',
    'target.house': 'House',
    'target.comet': 'Comet',
    'target.pyramid': 'Pyramid',
    'target.planet': 'Planet',
    'target.snowflake': 'Snowflake',
    'target.rainbow': 'Rainbow',
    'target.flag': 'Flag',
    'target.saturn': 'Saturn',
    'target.galaxy': 'Galaxy',
    'target.bucket': 'Bucket',
    'target.balloon': 'Balloon',
    'target.bus': 'Bus',
    'target.backpack': 'Backpack',
    'target.rocket': 'Rocket',
    'target.ufo': 'UFO',
    'target.mitten': 'Mitten',
    'target.sled': 'Sled',
    'target.shield': 'Shield',
    'seek.toMap': 'Back to map',
    'seek.move': 'Move',
    'seek.trace': 'Trace',
    'quest.animal': 'animal',
    'quest.food': 'food',
    'quest.shape': 'shape',
    'quest.toy': 'toy',
    'quest.nature': 'flower',
    'slot.title': 'Who is playing?',
    'slot.new': 'New',
    'slot.continue': 'Continue',
    'slot.reset': 'Reset',
    'slot.free': 'Free Mode',
    'slot.pick': 'Pick one',
    'slot.cancel': 'Back',
    'slot.changeAvatar': 'Change picture',
  },
};

/// localeCode('ja'|'en') と key から表示文字列を返す。未定義は ja → key の順でフォールバック。
String tr(String localeCode, String key) {
  return _strings[localeCode]?[key] ?? _strings['ja']?[key] ?? key;
}
