const Map<String, Map<String, String>> _strings = {
  'ja': {
    'app.title': 'たからさがし',
    'home.title': 'たからの ちず',
    'home.locked': 'ロック',
    'home.cleared': 'クリア',
    'home.modeEasy': 'やさしい',
    'home.modeNormal': 'ふつう',
    'home.modeHard': 'むずかしい',
    'settings.title': 'せってい',
    'settings.language': 'ことば',
    'seek.complete': 'クリア！！\n全て みつけたね',
    'scene.scene01.title': 'もりの たからさがし',
    'scene.scene02.title': 'うみの たからさがし',
    'scene.scene03.title': 'そらの たからさがし',
    'scene.scene04.title': 'やまの たからさがし',
    'scene.scene05.title': 'よるの たからさがし',
    'scene.scene06.title': 'さばくの たからさがし',
    'scene.scene07.title': 'うちゅうの たからさがし',
    'scene.scene08.title': 'うみのなかの たからさがし',
    'scene.scene09.title': 'ゆきやまの たからさがし',
    'scene.scene10.title': 'はなばたけの たからさがし',
    'scene.scene11.title': 'にじのおかの たからさがし',
    'scene.scene12.title': 'おしろの たからさがし',
    'target.apple': 'りんご',
    'target.duck': 'あひる',
    'target.star': 'ほし',
    'target.ball': 'ボール',
    'target.flower': 'おはな',
    'target.heart': 'ハート',
    'seek.toMap': 'ちずに もどる',
    'slot.title': 'だれが あそぶ?',
    'slot.new': 'あたらしく',
    'slot.continue': 'つづき',
    'slot.reset': 'リセット',
    'slot.free': 'フリーモード',
    'slot.pick': 'どれに する?',
    'slot.cancel': 'もどる',
  },
  'en': {
    'app.title': 'Treasure Hunt',
    'home.title': 'Treasure Map',
    'home.locked': 'Locked',
    'home.cleared': 'Cleared',
    'home.modeEasy': 'Easy',
    'home.modeNormal': 'Normal',
    'home.modeHard': 'Hard',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'seek.complete': 'Clear!!\nYou found them all!',
    'scene.scene01.title': 'Forest Hunt',
    'scene.scene02.title': 'Ocean Hunt',
    'scene.scene03.title': 'Sky Hunt',
    'scene.scene04.title': 'Mountain Hunt',
    'scene.scene05.title': 'Night Hunt',
    'scene.scene06.title': 'Desert Hunt',
    'scene.scene07.title': 'Space Hunt',
    'scene.scene08.title': 'Undersea Hunt',
    'scene.scene09.title': 'Snowy Hunt',
    'scene.scene10.title': 'Flower Field Hunt',
    'scene.scene11.title': 'Rainbow Hills Hunt',
    'scene.scene12.title': 'Castle Hunt',
    'target.apple': 'Apple',
    'target.duck': 'Duck',
    'target.star': 'Star',
    'target.ball': 'Ball',
    'target.flower': 'Flower',
    'target.heart': 'Heart',
    'seek.toMap': 'Back to map',
    'slot.title': 'Who is playing?',
    'slot.new': 'New',
    'slot.continue': 'Continue',
    'slot.reset': 'Reset',
    'slot.free': 'Free Mode',
    'slot.pick': 'Pick one',
    'slot.cancel': 'Back',
  },
};

/// localeCode('ja'|'en') と key から表示文字列を返す。未定義は ja → key の順でフォールバック。
String tr(String localeCode, String key) {
  return _strings[localeCode]?[key] ?? _strings['ja']?[key] ?? key;
}
